name: singify
description: A music lyrics app based on Figma design.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5  # Untuk state management
  audio_service: ^0.18.10  # Untuk layanan audio background
  just_audio: ^0.9.34  # Untuk pemutaran audio
  cached_network_image: ^3.2.3  # Untuk caching gambar
  font_awesome_flutter: ^10.6.0  # Untuk FontAwesome icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/album_covers/