name: singify
description: A music lyrics app based on Figma design.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5  # Untuk state management
  audio_service: ^0.18.10  # Untuk layanan audio background
  cached_network_image: ^3.2.3  # Untuk caching gambar
  font_awesome_flutter: ^10.6.0  # Untuk FontAwesome icons
  pocketbase: ^0.22.0
  http: ^1.3.0
  shared_preferences: ^2.2.0
  logger: ^2.0.0
  just_audio: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  